version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo

  cleansecpy:
    image: cleansecpy
    container_name: cleansecpy
    volumes:
      - "./cleansecpy/:/usr/src/cleansecpy"
    ports:
      - "5000:5000"
    external_links:
      - mongo
    depends_on:
      - mongo
