version: '3.9'

services:
  cleansecpy:
    image: cleansecpy
    container_name: cleansecpy
    volumes:
      - "./cleansecpy/:/usr/src/cleansecpy"
    ports:
      - "5000:5000"

  database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: cleanarchitecture
      POSTGRES_DB: cleanarchitecture